N9K1:
  groups:
  - nxos
  hostname: 192.168.128.41
  password: Admin123!
  port: 22
  username: admin
N9K2:
  groups:
  - nxos
  hostname: 192.168.128.42
  password: Admin123!
  port: 22
  username: admin
